Código/HouseHub/HouseHubWeb/Controllers/ImovelController.cs
using AutoMapper;
using Core.Service;
using HouseHubWeb.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace HouseHubWeb.Controllers
{
    [Authorize]
    public class ImovelController : Controller
    {

        private readonly IImovelService imovelService;
        private readonly IPessoaService pessoaService;
        private readonly IImagemService imagemService;
        private readonly IFileStorageService fileStorageService;
        private readonly IMapper mapper;

        public ImovelController(IImovelService imovelService, IPessoaService pessoaService, IImagemService imagemService, IFileStorageService fileStorageService, IMapper mapper)
        {
            this.imovelService = imovelService;
            this.pessoaService = pessoaService;
            this.imagemService = imagemService;
            this.fileStorageService = fileStorageService;
            this.mapper = mapper;
        }



        // GET: ImovelController
        public async Task<ActionResult> Index()
        {
            var imoveis = imovelService.GetAll().ToList();
            var model = mapper.Map<List<ImovelViewModel>>(imoveis);

            // Carregar a primeira imagem para cada imóvel
            foreach (var imovelViewModel in model)
            {
                var imagens = await imagemService.GetImagensByImovelIdAsync((uint)imovelViewModel.Id);
                imovelViewModel.ImagemPrincipalUrl = imagens.FirstOrDefault()?.Url;
            }

            return View(model);
        }

        // GET: ImovelController/Details/5
        public ActionResult Details(int id)
        {
            var imovel = imovelService.Get((uint)id);
            var model = mapper.Map<ImovelViewModel>(imovel);
            return View(model);
        }

        // GET: ImovelController/Create
        public ActionResult Create()
        {
            ViewBag.Tipos = new List<SelectListItem>
            {
                new SelectListItem { Text = "Casa", Value = "Casa" },
                new SelectListItem { Text = "Apartamento", Value = "Apartamento" }
            };
            return View();
        }

        // POST: ImovelController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ImovelViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PodeAnimal = (byte)(model.PodeAnimalBool ? 1 : 0);
                    var imovel = mapper.Map<Core.Imovel>(model);
                    string modalidade = model.PrecoVenda != null & model.PrecoAluguel != null?
                        "Ambos" : model.PrecoAluguel != null & model.PrecoVenda == null  ? "Aluguel" : "Venda";
                    imovel.Modalidade = modalidade;
                    imovel.Status = "Disponivel";

                    if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        string name = User.Identity.GetUserName();
                        uint id = pessoaService.GetUserByEmail(name);
                        imovel.IdPessoa = id;
                    }
                    
                    uint imovelId = imovelService.Create(imovel);

                    // Processar imagens se existirem
                    if (model.ImageFiles != null && model.ImageFiles.Count > 0)
                    {
                        // Salvar os arquivos fisicamente
                        List<string> imageUrls = await fileStorageService.SaveImagesAsync(model.ImageFiles);

                        // Salvar as URLs no banco de dados e associar ao imóvel
                        foreach (var url in imageUrls)
                        {
                            var imagem = new Core.Imagem
                            {
                                Url = url
                            };

                            // Salvar a imagem no banco
                            uint imagemId = await imagemService.CreateAsync(imagem);

                            // Associar a imagem ao imóvel
                            await imagemService.AssociarImagemAoImovelAsync(imovelId, imagemId);
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }

                ViewBag.Tipos = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Casa", Value = "Casa" },
                    new SelectListItem { Text = "Apartamento", Value = "Apartamento" }
                };
                return View(model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Erro ao tentar criar o imóvel: " + ex.Message);
                ViewBag.Tipos = new List<SelectListItem>
                {
                    new SelectListItem { Text = "Casa", Value = "Casa" },
                    new SelectListItem { Text = "Apartamento", Value = "Apartamento" }
                };
                return View(model);
            }
        }


        // GET: ImovelController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ImovelController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ImovelViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var imovel = mapper.Map<Core.Imovel>(model);
                    imovelService.Update(imovel);
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // GET: ImovelController/Delete/5
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var imovel = imovelService.Get((uint)id);
            var model = mapper.Map<ImovelViewModel>(imovel);
            return View(model);
        }

        // POST: ImovelController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection imovel)
        {
            try
            {
                imovelService.Delete((uint)id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(imovel);
            }
        }
    }
}

Código/HouseHub/HouseHubWeb/Controllers/MeusImoveisController.cs
using Core.Service;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service;

namespace HouseHubWeb.Controllers
{
    [Authorize]
    public class MeusImoveisController : Controller
    {

        private readonly IImovelService imovelService;
        private readonly IPessoaService pessoaService;

        public MeusImoveisController(IImovelService imovelService, IPessoaService pessoaService)
        {
            this.imovelService = imovelService;
            this.pessoaService = pessoaService;
        }

        public IActionResult Index()
        {
            uint idPessoa = pessoaService.GetUserByEmail(User.Identity.GetUserName());
            var imoveis = imovelService.GetMeusImoveis(idPessoa).ToList();
            return View(imoveis);
        }
    }
}

Código/HouseHub/HouseHubWeb/Views/Shared/Sobre.cshtml
@page
@model HouseHubWeb.Views.Shared.SobreModel
@{
}

Código/HouseHub/HouseHubWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HouseHubWeb</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HouseHubWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="background: transparent" height="50px" src="~/img/houseHub__b.svg" title="Voltar ao início"/>
                </a>
                <div>
                    <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">

                        <ul class="navbar-nav flex-grow-1 m-2">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="buscarimovel" asp-action="">Buscar imóveis</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Imovel" asp-action="Index">Para proprietários</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="MeusImoveis" asp-action="">Para locadores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="" asp-action="Sobre">Sobre</a>
                            </li>
                            <li id="Notificacao" class="nav-item">
                                <img style="background: transparent" height="30px" src="~/img/bell-solid.svg" />
                                <span class="badge" id="numeroNotificacao">
                                    2
                                </span>
                            </li>
                            <li class="nav-item">
                                <partial name="_LoginPartial" />
                            </li>
                        </ul>
                       
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>